name: encryption_app
description: Encrypt text with password
publish_to: 'none'
version: 6.10.0+28

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  bot_toast: ^4.1.3
  clipboard: ^0.1.3
  package_info_plus: ^8.2.1
  smooth_page_indicator: ^1.2.0+3
  sizer: ^3.0.5
  easy_localization: ^3.0.7+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  selectable_autolink_text: ^2.6.0
  in_app_review: ^2.0.10
  showcaseview: ^4.0.1
  local_auth: ^2.3.0
  flutter_inset_box_shadow:
    path: packages/flutter_inset_box_shadow-1.0.8
  receive_sharing_intent: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  mockito: ^5.4.5
  flutter_lints: ^5.0.0

dependency_overrides:
  win32: ^5.10.1
  lints: ^5.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - fonts/baloo/

  fonts:
    - family: Baloo
      fonts:
        - asset: fonts/baloo/BalooBhaijaan2-Regular.ttf
          weight: 500


    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
