name: encryption_app
description: Encrypt text with password
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 6.6.0+19

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bot_toast: ^4.0.2
  clipboard: ^0.1.3
  package_info: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  sizer: ^2.0.15
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.2
  share_plus: ^7.0.2
  selectable_autolink_text: ^2.3.0
  in_app_review: ^2.0.6
  showcaseview: ^2.0.3
  local_auth: ^1.1.10
  flutter_inset_box_shadow: ^1.0.8
  receive_sharing_intent: ^1.4.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.5
  mockito: ^5.2.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
#        - asset: fonts/Cairo-ExtraLight.ttf
#          weight: 200
#        - asset: fonts/Cairo-Light.ttf
#          weight: 300
        - asset: fonts/Cairo-Regular.ttf
          weight: 400
#        - asset: fonts/Cairo-Medium.ttf
#          weight: 500
        - asset: fonts/Cairo-Bold.ttf
          weight: 600
#        - asset: fonts/Cairo-SemiBold.ttf
#          weight: 700
#        - asset: fonts/Cairo-ExtraBold.ttf
#          weight: 800
#        - asset: fonts/Cairo-Black.ttf
#          weight: 900


    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
