/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String _kFontPkg = null;

  static const IconData key_lock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_stars_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_stars = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_outline = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_outline = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_outline2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_stars_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_stars_outline2 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_stars = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_stars2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock2 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
